#!/usr/bin/env python3

#this is still work in progress, if you would like a specific feature, please ether submit an issue, or commit to the code
#Auther:  Artemis-Arrow
import dearpygui.dearpygui as dpg
import os

#functions

#adb functions

def adbrebootloader(sender, data):
    os.system("adb reboot bootloader")

def adbrebootrecovery(sender, data):
    os.system("adb reboot recovery")

#fastboot functions

def flashvbmeta(sender, data):
    imagepath = data['file_path_name']
    os.system("fastboot --disable-verity --disable-verification flash vbmeta " + imagepath)

def eraseusrdata(sender, data):
    os.system("fastboot erase userdata")

def erasecashe(sender, data):
    os.system("fastboot erase cache")

def flashboot(sender, data):
    imagepath = data['file_path_name']
    os.system("fastboot flash boot " + imagepath)

def bootloaderunlock(sender, data):
    os.system("fastboot oem unlock")

def bootloaderlock(sender, data):
    os.system("fastboot oem lock")

def devicereset(sender, data):
    os.system("fastboot -w")

#misc functions

def selectpathboot(sender, data):
    with dpg.file_dialog(directory_selector=False, show=True, callback=flashboot, id="file_dialog_id"):
        dpg.add_file_extension(".img")

def selectpathvbmeta(sender, data):
    with dpg.file_dialog(directory_selector=False, show=True, callback=flashvbmeta, id="file_dialog_id"):
        dpg.add_file_extension(".img")

def exit(sender, data):
     os._exit(0)

#create window
dpg.create_context()
dpg.create_viewport(title='FastBootGUI (rename later)', width=1920, height=1080)

with dpg.window(label=""):
    #adb
    dpg.add_button(label="reboot to bootloader", callback = adbrebootloader)
    dpg.add_button(label="reboot to recovery", callback = adbrebootrecovery)
    #fastboot
    dpg.add_button(label="flash boot image", callback = selectpathboot)
    dpg.add_button(label="flash vbmeta", callback = selectpathvbmeta)
    dpg.add_button(label="erase userdata", callback = eraseusrdata)
    dpg.add_button(label="erase cashe", callback = erasecashe)
    dpg.add_button(label="unlock bootloader", callback = bootloaderunlock)
    dpg.add_button(label="lock bootloader", callback = bootloaderlock)
    dpg.add_button(label="reset device", callback = devicereset)
    dpg.add_button(label="exit", callback = exit)

dpg.setup_dearpygui()
dpg.show_viewport()
dpg.start_dearpygui()
dpg.destroy_context()
